export GOPATH="$HOME/go"
export PATH="$PATH:/usr/local/go/bin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local/bin"
export PATH=$HOME/usr/local/bin:$PATH
export PATH=$HOME/Library/Android/sdk/platform-tools:$PATH
export PATH="$PATH:/Users/gerard/Library/Application Support/multipass/bin"
export PATH="$PATH:$(dirname $(func-e which))"
export PATH="$PATH:/Users/gerard/dev/istio/bin/dev"
